# Generated by Django 4.2 on 2023-04-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreePicturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('picture', models.ImageField(upload_to='picture/%Y/%m/%d/')),
                ('picture2', models.ImageField(blank=True, upload_to='picture/%Y/%m/%d/')),
                ('content', models.CharField(max_length=700)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
