# Generated by Django 4.2 on 2023-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_freepicturepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freepicturepost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='picture/%Y/%m/%d/'),
        ),
    ]
