# Generated by Django 4.2 on 2023-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='job',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='univ',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
