# Generated by Django 4.2 on 2023-04-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_myuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='job_group',
            field=models.CharField(default='기타', max_length=20),
        ),
    ]
