# Generated by Django 4.2 on 2023-04-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_job_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='job_group',
            field=models.CharField(choices=[('경영,사무,금융,보험직', '경영,사무,금융,보험직'), ('연구,공학,기술직', '연구,공학,기술직'), ('교육,법률,사회복지,경찰,소방직 및 군인', '교육,법률,사회복지,경찰,소방직 및 군인'), ('보건,의료직', '보건,의료직'), ('예술,디자인,방송,스포츠직', '예술,디자인,방송,스포츠직'), ('미용,경비,청소직', '미용,경비,청소직'), ('영업등', '영업,판매,운전,운송직'), ('영업,판매,운전,운송직', '건설,채굴직'), ('설치,정비,생산직', '설치,정비,생산직'), ('농립어업직', '농립어업직'), ('기타', '기타')], default='기타', max_length=30),
        ),
    ]
