# Generated by Django 4.2 on 2023-05-01 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_remove_myblog_bloguser'),
        ('accounts', '0006_alter_myuser_job_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='blog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.myblog'),
        ),
    ]
