# Generated by Django 4.2 on 2023-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='blog_intro',
            field=models.TextField(default='블로그 설명을 작성해주세요'),
        ),
        migrations.AddField(
            model_name='myblog',
            name='blog_name',
            field=models.CharField(default='익명의 블로그', max_length=20),
        ),
    ]
