# Generated by Django 4.2 on 2023-04-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_myblog_blog_intro_myblog_blog_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myblog',
            old_name='user',
            new_name='Bloguser',
        ),
    ]
