# Generated by Django 4.2 on 2023-05-01 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0003_rename_user_myblog_bloguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='Bloguser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloguser', to=settings.AUTH_USER_MODEL),
        ),
    ]
